services:
  - type: web
    name: geniusbabycosmetics
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: geniusbabycosmetics
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: ADMIN_TOKEN
        sync: false
